# Generated by Django 5.2 on 2025-04-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainztrackr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allexercises',
            old_name='video_url',
            new_name='image_url',
        ),
    ]
