# Generated by Django 5.2 on 2025-04-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainztrackr', '0004_category_equipment_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allexercises',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gainztrackr.category'),
        ),
        migrations.AlterField(
            model_name='allexercises',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gainztrackr.equipment'),
        ),
    ]
