# Generated by Django 5.2 on 2025-04-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainztrackr', '0005_alter_allexercises_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allexercises',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
