# Generated by Django 5.2 on 2025-04-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gainztrackr', '0006_alter_allexercises_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allexercises',
            name='category',
        ),
    ]
